### ISSUE TITLE
Add support for the new Tax Calculations

### ISSUE THREAD

**Issue by jallum** [stripe/openapi#102]
[Tax Calculations](https://stripe.com/docs/api/tax/calculations) are in the docs, but haven't yet been added to the OpenAPI specs yet. Can someone please do that, so that I can update my client library to use them?

**Comment by pakrym-stripe** [comment]
Tax calculations are a beta feature so they won't appear in the main spec. They are part of the [beta spec](https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.beta.sdk.json).
