### ISSUE TITLE
Undocumented fields on charge and refund fixtures

### ISSUE THREAD

**Issue by mjadczak** [stripe/openapi#11]
This issue is very similar to #6. `charge` and `refund` fixtures contain fields which are not documented in the official docs.

```
21:55:32.464 [error] Extra keys were received but ignored when converting Stripe object charge: [:alternate_statement_descriptors, :application_fees_refunded, :application_fees_refunded_currency, :authorization_code, :captured_at, :fee_balance_transactions]

21:55:32.464 [error] Extra keys were received but ignored when converting Stripe object refund: [:description, :fee_balance_transactions, :type]
```

**Comment by brandur-stripe** [comment]
@mjadczak Can you pull a fresh version of the fixtures from this repo? I'm not sure what changed exactly, but I don't think those [fields are in the fixture data anymore](https://github.com/stripe/openapi/blob/bc5b376ff0882e86c77f3a960b3c1ac28118ff2f/openapi/fixtures2.yaml#L398-L454).

**Comment by mjadczak** [comment]
I'm getting this using stripe-mock v0.1.23, it looks like it's using an older version of these fixtures?

**Comment by brandur-stripe** [comment]
> I'm getting this using stripe-mock v0.1.23, it looks like it's using an older version of these fixtures?

Ah, yes. We're going to update them, but I was waiting for https://github.com/stripe/stripe-mock/pull/17 to fall into place (which will handle it), although we could plausibly do it sooner too.

@tmaxwell-stripe Any feeling for how close we are to merging that?

**Comment by mjadczak** [comment]
Oh, nice. There's no rush on this from my end—it's just a diagnostic message, the library correctly just ignores the extra fields. In that case I'm closing this. Thanks!

**Comment by tmaxwell-stripe** [comment]
@brandur-stripe Optimistically Friday.
