### ISSUE TITLE
spec3 contains $refs to "#/definitions/error"

### ISSUE THREAD

**Issue by MikeRalphson** [stripe/openapi#12]
These should all be "#/components/schemas/error"

With that, the spec passes my [validator](https://github.com/mermade/swagger2openapi).

**Comment by brandur-stripe** [comment]
Thanks. I've pushed a fix in 9c43ace (that also includes a few other updates).

> With that, the spec passes my validator.

Great to hear!  We're also validating internally against the experiment JSON schema for OpenAPI 3.0.
