### ISSUE TITLE
Missing BETA issuing APIs

### ISSUE THREAD

**Issue by payellodevsupport** [stripe/openapi#123]
The following APIs are missing from the beta spec:

- /v1/issuing/tokens
- /v1/issuing/programs

**Comment by pakrym-stripe** [comment]
Hi @payellodevsupport, thank you for your interest. APIs are included in beta SDKs/spec on opt in basis when teams see interest from their customers. I've notified the team directly but it might also help if you reach out to https://support.stripe.com/contact and state your interest.
