### ISSUE TITLE
file_upload schema values for purpose

### ISSUE THREAD

**Issue by joshsmith** [stripe/openapi#13]
I've seen instances where `file_upload` objects have a purpose with values of `"business_logo"` or even `"sigma_scheduled_query"`. Neither the schema nor the hosted API docs indicate these as possible values. Should the spec be updated to include these, and are there others we're missing?

**Comment by brandur-stripe** [comment]
Thanks Josh!

So I think in this case the inconsistency was just because the spec hadn't been pushed to this repository in a while. I just committed e9d2beb67f9280e29ad70139c1ae8ab0cbd4b3b3 and it brings along the `purpose` field.
