### ISSUE TITLE
operationIds are not unique

### ISSUE THREAD

**Issue by MikeRalphson** [stripe/openapi#14]
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API

It appears to be 

```yaml
operationId: AllTransactions
```

Which is the culprit. Applies to both `spec2` and `spec3`.

**Comment by brandur-stripe** [comment]
Yeah, we're using an internal name to generate these right now and the results aren't great.

I think we'll probably just work around it relatively cheaply by generating names that are based on verb and path.

cc @tmaxwell-stripe

**Comment by kvnamipara** [comment]
In the latest update of openapi schemas, 'DeleteCustomerDiscount' operation is not unique. Two different APIs are having same operation Id 'DeleteCustomerDiscount'.

**Comment by brandur-stripe** [comment]
@tmaxwell-stripe @mickjermsurawong-stripe Given that you guys have been doing a lot of work on the spec recently, any chance you want to take a crack at this? Seems like a pretty easy thing to resolve.

**Comment by mickjermsurawong-stripe** [comment]
acked @brandur-stripe! I will take up the issue.

**Comment by mickjermsurawong-stripe** [comment]
I'll close this issue for now, but please let me know if you encounter problems on this.
