### ISSUE TITLE
Automatic pulling latest spec3.json per new Stripe OpenAPI release? 

### ISSUE THREAD

**Issue by jeff00seattle** [stripe/openapi#143]
I have a service that automatically resolves **npm dependencies** within an application's **package.json**.

My application has a dependency that its available **Stripe's OpenAPI spec3.json** must be its **latest release**.

Would you happen to know of examples of how to monitor for **[releases](https://github.com/stripe/openapi/releases)** and then download the [latest](https://github.com/stripe/openapi/blob/master/openapi/spec3.json)?

Thank you
And Merry Christmas

**Comment by pakrym-stripe** [comment]
I'm sorry, this is an issue tracker for issues with Stripe OpenAPI definitions. There are more appropriate forums (StackOverflow) for general programming questions.

**Comment by jeff00seattle** [comment]
🎅 👍
