### ISSUE TITLE
account schema missing transfers_enabled?

### ISSUE THREAD

**Issue by joshsmith** [stripe/openapi#16]
The `account` schema maybe appears to be missing `transfers_enabled`.

I'm not sure if this key went away with a new version of the API, but it does seem to indicate that we're perhaps not able to use different versions of this spec for different API versions. Is that accurate?

**Comment by garethson** [comment]
This also seems to have disappeared for me when I updated my API version. There is now `payouts_enabled`, which correlates with Stripes changes on this. https://stripe.com/docs/transfer-payout-split

**Comment by pakrym-stripe** [comment]
I apologize for the extremely delayed response. `transfers_enabled` was indeed renamed to `payouts_enabled` as part of Transfer-Payout split.
