### ISSUE TITLE
Use more definitions instead of repeating type data?

### ISSUE THREAD

**Issue by mohawk2** [stripe/openapi#21]
Hi, in at least the v2 spec, in JSON Pointer speak this:

```
/paths/~1v1~1accounts/post/parameters/0/schema/properties/legal_entity/additional_owners/properties
```

has string keys of "0", "1", ... and each of those values is identical:

```
                        "0": {
                          "properties": {
                            "address": {
                              "properties": {
                                "city": {
                                  "type": [
                                    "string"
                                  ]
                                },
```

etc. These could all each instead be: 

```
                        "0": { "$ref": "#/definitions/legal_entity_definition" },
```

or similar. Out of the currently 41k line spec, that would already save about 100 x 30 = 3k. There are probably more examples.

**Comment by brandur-stripe** [comment]
Thanks for logging. And yes, it seems like a good idea to fix this.

I'm not sure I'll get to this soon as this part of the generator is a little involved. If size is a problem I'd suggest compression — even without these duplicates the spec is highly repetitive and a gzip should work really well.

**Comment by mohawk2** [comment]
If you'd publish that code I'd be pleased to provide a fix myself. However I'm more concerned with the "type is an array" incompatibility or the non-unique `operationId`!

**Comment by pakrym-stripe** [comment]
I apologize for the extremely delayed response. This has been fixed. We don't generate numerical string keys with duplicated values anymore.
