### ISSUE TITLE
Generating openapi?

### ISSUE THREAD

**Issue by bootstraponline** [stripe/openapi#25]
How are you generating the openapi? The bin script looks like it copies the files out of `~/stripe/pay-server/`. I'm wondering if you're using a library to generate the OpenAPI JSON from the code.

**Comment by brandur-stripe** [comment]
@bootstraponline We generate it from an internal DSL of our API, from the API's main project directory. Everything in there is _extremely_ custom, and unfortunately I doubt that it would have any practical value for re-use outside of Stripe.

**Comment by bootstraponline** [comment]
Thanks!
