### ISSUE TITLE
operationId's not unique

### ISSUE THREAD

**Issue by dflorey** [stripe/openapi#27]
The operationId's are not unique in the stripe spec, e.g. the operationId "DeleteAccountExternalAccount" appears 4 times.

Spec:
operationId: "Unique string used to identify the operation. The id MUST be unique among all operations described in the API."

**Comment by brandur-stripe** [comment]
Going to close this as a dup of #14.

@tmaxwell-stripe Correct me if I'm wrong, but you were working on this one right?
