### ISSUE TITLE
Consistency between review.rules_features.card_brand/card_country and source.brand/country 

### ISSUE THREAD

**Issue by jleclanche** [stripe/openapi#28]
Hey -- I'm guessing this isn't the correct tracker for this, but wasn't sure where to file this issue.

Here are parts of a review and card object, identifying the same card (as part of a single charge being reviewed):

```json
{
  "review": {
    "id": "prv_XXXXXXXXXXXXXXXXXXX",
    "object": "review",
    "charge": "ch_XXXXXXXXXXXXXXXXXXXXXXXX",
    "rules_features": {
      "card_brand": "visa",
      "card_country": "fr",
      "card_funding": "credit",
      "ip_country": "fr",
      "risk_level": "normal",
      "risk_score": null
    }
  },
  "source": {
    "id": "card_XXXXXXXXXXXXXXXXXXXXXXXX",
    "object": "card",
    "address_city": null,
    "address_country": null,
    "address_line1": null,
    "address_line1_check": null,
    "address_line2": null,
    "address_state": null,
    "address_zip": null,
    "address_zip_check": null,
    "brand": "Visa",
    "country": "FR"
  }
}
```

The results of country and brand have different capitalization. This is a little frustrating because it means they require separate enums (albeit essentially identical ones).

Could this inconsistency be resolved? Lowercase makes the most sense but I also know that the card brand enum (with its whitespace and mixed case) is well established by now, unlike the review one...

**Comment by brandur** [comment]
Hi @jleclanche,

So I have to admit that I don't have the benefit of knowing the history of this decision, but these are actually two different enums, and for maximum correctness, they should be treated as such.

`card_brand` under `review` is actually a brand abbreviation like `amex` or `dscvr`. See [here for details](https://stripe.com/docs/radar/rules/reference#supported-attributes).

`brand` under source is a complete brand name like `American Express` or `Discover`. See [here for details](https://stripe.com/docs/api/java#card_object-brand).

**Comment by jleclanche** [comment]
Any chance these could be considered for consolidation? Its a minor issue
but a paper cut nonetheless.

**Comment by richardm-stripe** [comment]
Hello @jleclanche, I am closing this issue. I don't think unifying these properties is something we are going to pursue.
