### ISSUE TITLE
platform_earning, platform_fee, backwards_compatible_platform_earning

### ISSUE THREAD

**Issue by jleclanche** [stripe/openapi#37]
I guess similar question as #32. The spec lists all three and it's unclear to me which is which. It's even unclear to me which of these represents the [endpoint documented here](https://stripe.com/docs/api#application_fee_object).

**Comment by brandur-stripe** [comment]
Yeah, this is some internal implementation being revealed in that this is how related but separate concerns are modeled in our backend.

The good news is that we have a unification project that should be coming along pretty soon that'll create unified facades for this type of resource.

**Comment by jleclanche** [comment]
Yay, awesome.

Do you know which model I should use as reference for now?

**Comment by jleclanche** [comment]
According to the `fee_refund` object I'm looking for `platform_fee`.

**Comment by jleclanche** [comment]
Is there no `livemode` attribute on `fee_refund`?

**Comment by richardm-stripe** [comment]
Hello @jleclanche, sorry for the long period without a response

It looks like
- The unification project brandur mentioned has come to fruition and the duplicate object definitions here are no more.
- There is indeed no `livemode` attribute on `fee_refund`
