### ISSUE TITLE
How can I use the spec2.json with oasgraph?

### ISSUE THREAD

**Issue by haalcala** [stripe/openapi#45]
I keep getting:

OASGraph creation event error:  Invalid schema for bearerAuth provided of type "undefined".

So, where should I put the api_key?

**Comment by brandur-stripe** [comment]
We can't lend support for specific tools, but you can read [how to authenticate against Stripe](https://stripe.com/docs/api/authentication?lang=curl) in our API documentation. The easiest way is to use `Bearer` in an `Authorization` header like: `-H "Authorization: Bearer sk_test_123"`.
