### ISSUE TITLE
spec3 vs spec3.sdk

### ISSUE THREAD

**Issue by andrewsolomon** [stripe/openapi#48]
A newbie question here - I'm trying to understand the difference between `openapi/spec3.json` and `openapi/spec3.sdk.json`. Could you explain the context for using these two specs?

**Comment by clement911** [comment]
I have the same question. Anyone?

**Comment by remi-stripe** [comment]
@andrewsolomon @clement911 Sorry for the delays here!

The `openapi/spec3.json` file matches our publicly documented API, the one you can see in the API reference.

When we started generating client libraries, we ended up building support for features that are not yet public but that users might rely on before it's officially in our API reference. This can happen for multiple reasons such as
* a feature being private and limited but used by enough users to require the client libraries we maintain to support it.
* a feature being stable but in private beta before we release it publicly.
* a feature we have deprecated but need to keep in the client libraries (such as stripe-java) until the next major version to avoid releasing a breaking change for every small incompatible changes. A good example is a string field becoming an enum for example.

To support all those cases, we built a separate version of the spec, `openapi/spec3.sdk.json`, which mirrors the official one but has a few extra features in it.
If you are maintaining client libraries yourself then I would recommend monitoring openapi/spec3.sdk.json` specifically!

**Comment by clement911** [comment]
Got it! That makes perfect sense.
Might be worth adding this explanation in the readme.
