### ISSUE TITLE
Incorrect expandable fields

### ISSUE THREAD

**Issue by clement911** [stripe/openapi#54]
Hi there,

It seems to me that some fields have been incorrectly defined as expandable fields.

Here are a few that are marked as expandable in [spec3.json](https://github.com/stripe/openapi/blob/master/openapi/spec3.json) but that are not labeled as expandable in the API docs.

**account:**
 business_profile,capabilities,company,individual,requirements,settings,tos_acceptance

**balance:**
available,connect_reserved,pending

**customer:**
address,invoice_settings,shipping

And more...

Unless I'm missing something?

**Comment by remi-stripe** [comment]
Those fields are hashes/dictionaries so on our end they are considered expandable and are always auto-expanded. It's definitely something we could clean up in the future and only tag as expandable properties that are real API resources but it's not something we're focusing on at the moment. Especially as we're adding expandable scalar fields where it means that the field can be absent unless explicitly expanded (as we discussed in the stripe-dotnet repo).

I'm going to tag as `future` though as it's definitely something I would like to represent better in the future.

**Comment by clement911** [comment]
I see.
Maybe the spec could clearly indicate which fields are auto-expanded, and which fields are expandable on demand?
If someone were to use the spec to generate a tool that leverages the API, one would really care about the fields that are expandable and not the one that are auto-expanded (since there is nothing the tool could do to impact the API behaviour there).
(I assumed this spec was for external consumption but maybe you built it for internal consumption at Stripe?)

**Comment by remi-stripe** [comment]
The spec should be self-sufficient here and have all relevant information based on the type of each object/hash and it should be enough. We know some developers have built their own tool ingesting the spec and generating the library for their language like we do internally for most!
I agree we could make this clearer though and it's something we've discussed as a potential future improvement!

**Comment by clement911** [comment]
OK.

It would be useful I think

For example, I might want to generate a tool to generate API calls and let the users choose which fields they want to expand (it could be a library or visual tool or whatever).
In this context, I only want to show the user the expandable fields and not the auto expanded ones.

Thanks for listening as usual. I'm closing this.
