### ISSUE TITLE
Request: Recurring coupon support for non-monthly periods

### ISSUE THREAD

**Issue by jonesmattc** [stripe/openapi#57]
Hello,

Currently, Stripe Subscriptions and Prices allow me to set a recurring period of days, months, years, etc but the Coupon object I attach to those subscriptions only understands months.

I would like it if the coupon object either prorated (a coupon recurring 2 months took [2/12]% off an annual payment one time) or for coupons to understand different billing periods than monthly.

If this is the wrong place for this request, please let me know and I'd be happy to make it in the right place. In general, I think the coupon objects could use some love, especially after the improvements brought about by the new Prices API.

**Comment by remi-stripe** [comment]
@jonesmattc Thanks for the feedback! I'd recommend reaching out to our support team for something like this instead. You can contact them here: https://support.stripe.com/contact
