### ISSUE TITLE
Undocumented file upload purposes

### ISSUE THREAD

**Issue by jleclanche** [stripe/openapi#58]
https://stripe.com/docs/api/files/object#file_object-purpose

I found that at least the two following possible values are not mentioned:

- `document_provider_identity_document`
- `invoice_statement`

I don't know if there are other missing ones.

**Comment by remi-stripe** [comment]
@jleclanche Thanks for reaching out! Those enums are "secret" in the sense that they are not in our public API and you usually need a custom feature enabled to see them. They should not be in the API reference and we'll work on a fix internally!

**Comment by remi-stripe** [comment]
Ah my bad, I misunderstood your ask. So yeah it's expected, it's just that some values can exist on some specific accounts with a feature enabled!

**Comment by jleclanche** [comment]
Are you sure? I encountered them in live data.
