### ISSUE TITLE
Missing `payment_method_options.card.three_d_secure`

### ISSUE THREAD

**Issue by dgaspar** [stripe/openapi#80]
Both "public" and "internal" OpenAPI specs seem to be missing the documented [`three_d_secure`](https://stripe.com/docs/api/payment_intents/confirm#confirm_payment_intent-payment_method_options-card-three_d_secure) property for the schema `payment_intent_payment_method_options_card`.
Is there a plan for adding it? Or am I missing something?

**Comment by pakrym-stripe** [comment]
Hi. I apologize for the extremely delayed response `request_three_d_secure` is now available on `payment_intent_payment_method_options_card`
