### ISSUE TITLE
Retrieve events by related_object=<customer id>

### ISSUE THREAD

**Issue by ken-scarf** [stripe/openapi#87]
We can currently curl events with parameter `related_objects=<customer id>` but this is currently not documented. Is it safe to do this? or will this change without notice?

**Comment by remi-stripe** [comment]
@ken-scarf it is not safe to do this and it would change without notice. It's a feature we use for our UIs in the Dashboard and it is not part of our official API so you should not rely on it.

**Comment by ken-scarf** [comment]
thanks @remi-stripe
