### ISSUE TITLE
Order Return Object has Disappeared

### ISSUE THREAD

**Issue by erichCompSci** [stripe/openapi#92]
Hi, I can't seem to find the Order Return object in the latest spec.  The Webhooks Events API claims that order return creation events return Order Return objects (according to the public reference documentation).  What is the intended behavior here?  I'm working on a library that generates code from the open API so I need to understand this particular nuance here.

**Comment by remi-stripe** [comment]
@erichCompSci The Orders API has been considered legacy for a few years now and only seen limited use. We're rebuilding this API from the ground up and just recently released a beta: https://stripe.com/docs/orders

To better handle this upcoming new feature, we've removed the legacy Orders API from our client libraries, openapi and stripe-mock. In the future, we will add the newer APIs which will return a completely different object shapes (though still with `object: 'order'`

If you rely on the Legacy Orders API, you will have to pin to an older version of stripe-mock or mock the API responses yourself.

Let me know if you have a follow up questions.

**Comment by erichCompSci** [comment]
Okay, I understand.  I'll comment the code with the understanding that the event will have a different object in the future.  Thank you.
