### ISSUE TITLE
Question about subscription item quantity set to 0

### ISSUE THREAD

**Issue by mxp-qk** [stripe/openapi#93]
Hello  👋

I have some interrogation about the possibility to create a line item in a subscription with a quantity of 0.

I tried different way to do it : 

- via the Stripe interface (create a new subscription) : OK
- via the Stripe interface (Update an existing subscription) : OK
- via the Stripe API endpoint /v1/checkout/sessions (create a new subscription) : KO
- via the Stripe API endpoint /v1/subscription_items (update a new subscription) : OK

So it appears it is not possible to create a subscription via the API with an item quantity set to 0 (other items with quantity greater than 1 are in the request as well). Is this the expected behaviour or should be possible and I might miss something ?

Here the response from the API call
```json
Status code 400
{
  "error": {
    "code": "parameter_invalid_integer",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-integer",
    "message": "This value must be greater than or equal to 1.",
    "param": "line_items[1][quantity]",
    "type": "invalid_request_error"
  }
}
```

** Additional details **
The quantity is mark as optional in the API documentation but a call with a price ID but no quantity return this error

```json
Status code 400
{
  "error": {
    "message": "Quantity is required. Add `quantity` to `line_items[1]`",
    "param": "line_items[1]",
    "type": "invalid_request_error"
  }
}
```

Thank you for your help

**Comment by remi-stripe** [comment]
@mxp-qk Github issues are limited to bugs with the library itself. Here the question is more an integration question at the moment, better suited for our support team instead: https://support.stripe.com/contact

Overall this is just a limitation of Checkout today which won't let you choose a quantity that is lower than 1. The rest of the API supports it for various advanced use-cases, but Checkout doesn't and it'd be more a feature request. For now you can't use Checkout if you need a quantity set to 0!
